### ISSUE TITLE
Must modify the way to generate js codes from proto files

### ISSUE THREAD

**Issue by taiki1frsh** [cosmos-client/cosmwasm-ts#4]
As the structure of the proto management of `wasmd` repository has changed, the current way to generate the js files from proto files don't work.
We have to modify (or possibly radically change the client structure).

cc: @mkXultra @Senna46 

Specifically, gen-proto.sh, gen-openapi.sh requires raw dependent proto files (third-party protos) to generate ts files.
But, since the way to manage the dependent files changed, there's no longer third-party proto folder in `wasmd`.

So, have to change the way to manage dependent files in process to generate ts proto files in the both scripts.

**Comment by Senna46** [comment]
Seems to have been there until at least 2 months ago.
https://github.com/CosmWasm/wasmd/tree/upgrade_protos

When use this, follow error
```
Error: Unexpected token in option: .get
    at onoption (/home/user/.npm/_npx/08926cdeed955aef/node_modules/protocol-buffers-schema/parse.js:347:15)
    at onrpc (/home/user/.npm/_npx/08926cdeed955aef/node_modules/protocol-buffers-schema/parse.js:517:17)
    at onservice (/home/user/.npm/_npx/08926cdeed955aef/node_modules/protocol-buffers-schema/parse.js:449:30)
    at Function.parse (/home/user/.npm/_npx/08926cdeed955aef/node_modules/protocol-buffers-schema/parse.js:596:30)
    at Object.parseSchema (/home/user/.npm/_npx/08926cdeed955aef/node_modules/pbjs/index.js:6:27)
    at Object.<anonymous> (/home/user/.npm/_npx/08926cdeed955aef/node_modules/pbjs/cli.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
/home/user/.npm/_npx/08926cdeed955aef/node_modules/protocol-buffers-schema/parse.js:347
        throw new Error('Unexpected token in option: ' + tokens[0])
        ^
```

**Comment by Senna46** [comment]
In https://github.com/cosmos-client/ununifi-ts, there are same errors.
@taiki1frsy @mkXultra Do you know anything about its error?
